
pipeline {
    agent any
    tools {
        maven "maven3"
    }
    environment {
        NEXUS_VERSION = "nexus3"
        NEXUS_PROTOCOL = "http"
        NEXUS_URL = "13.201.57.133:8081"
        NEXUS_REPOSITORY = "my-nexus-snapshots"
        NEXUS_CREDENTIAL_ID = "nexus"
    }
    stages {
        stage("Clone code from GitHub") {
            steps {
                script {
                    git branch: 'main', credentialsId: 'git', url: 'https://github.com/PriyeshPandey07/Nexus-Repo-with-Jenkins.git';
                }
            }
        }
        stage("Maven Build") {
            steps {
                script {
                    sh "mvn clean compile package"
                    sh "mvn clean install" 
                    sh "mvn install -f pom.xml" 
                    sh "ls -l target/"
                    sh "mvn clean package deploy"
                }
            }
        }
    }    