
pipeline {
    agent any
    tools {
        maven "maven3"
    }
}
 
        stage("Maven Build") {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[credentialsId: 'git', url: 'https://github.com/PriyeshPandey07/Nexus-Repo-with-Jenkins.git']]]) {
                   
                   
                    sh "mvn clean compile package"
                    sh "mvn clean install" 
                    sh "mvn install -f pom.xml" 
                
                
                }
            }
        }
    }      